### ISSUE TITLE
[FE] webpack이 정상적으로 빌드되지 않아 node-sass 모듈을 package.json에 추가해야합니다.

### ISSUE THREAD

**Issue by ksundong** [codesquad-memeber-2020/signup-1#93]
에러 메시지
```
ERROR in ./scss/main.scss
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
Error: Cannot find module 'node-sass'
Require stack:
- /Users/idion/WorkSpace/codesquad/signup-1/FE/node_modules/sass-loader/dist/getDefaultSassImplementation.js
- /Users/idion/WorkSpace/codesquad/signup-1/FE/node_modules/sass-loader/dist/getSassImplementation.js
- /Users/idion/WorkSpace/codesquad/signup-1/FE/node_modules/sass-loader/dist/index.js
- /Users/idion/WorkSpace/codesquad/signup-1/FE/node_modules/sass-loader/dist/cjs.js
- /Users/idion/WorkSpace/codesquad/signup-1/FE/node_modules/loader-runner/lib/loadLoader.js
- /Users/idion/WorkSpace/codesquad/signup-1/FE/node_modules/loader-runner/lib/LoaderRunner.js
- /Users/idion/WorkSpace/codesquad/signup-1/FE/node_modules/webpack/lib/NormalModule.js
- /Users/idion/WorkSpace/codesquad/signup-1/FE/node_modules/webpack/lib/NormalModuleFactory.js
- /Users/idion/WorkSpace/codesquad/signup-1/FE/node_modules/webpack/lib/Compiler.js
- /Users/idion/WorkSpace/codesquad/signup-1/FE/node_modules/webpack/lib/webpack.js
- /Users/idion/WorkSpace/codesquad/signup-1/FE/node_modules/webpack-cli/bin/utils/validate-options.js
- /Users/idion/WorkSpace/codesquad/signup-1/FE/node_modules/webpack-cli/bin/utils/convert-argv.js
- /Users/idion/WorkSpace/codesquad/signup-1/FE/node_modules/webpack-cli/bin/cli.js
- /Users/idion/WorkSpace/codesquad/signup-1/FE/node_modules/webpack/bin/webpack.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:797:15)
    at Function.Module._load (internal/modules/cjs/loader.js:690:27)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (/Users/idion/WorkSpace/codesquad/signup-1/FE/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at getDefaultSassImplementation (/Users/idion/WorkSpace/codesquad/signup-1/FE/node_modules/sass-loader/dist/getDefaultSassImplementation.js:24:10)
    at getSassImplementation (/Users/idion/WorkSpace/codesquad/signup-1/FE/node_modules/sass-loader/dist/getSassImplementation.js:19:72)
    at Object.loader (/Users/idion/WorkSpace/codesquad/signup-1/FE/node_modules/sass-loader/dist/index.js:40:61)
    at /Users/idion/WorkSpace/codesquad/signup-1/FE/node_modules/webpack/lib/NormalModule.js:316:20
    at /Users/idion/WorkSpace/codesquad/signup-1/FE/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /Users/idion/WorkSpace/codesquad/signup-1/FE/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at runSyncOrAsync (/Users/idion/WorkSpace/codesquad/signup-1/FE/node_modules/loader-runner/lib/LoaderRunner.js:143:3)
    at iterateNormalLoaders (/Users/idion/WorkSpace/codesquad/signup-1/FE/node_modules/loader-runner/lib/LoaderRunner.js:232:2)
    at Array.<anonymous> (/Users/idion/WorkSpace/codesquad/signup-1/FE/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
    at Storage.finished (/Users/idion/WorkSpace/codesquad/signup-1/FE/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:55:16)
    at /Users/idion/WorkSpace/codesquad/signup-1/FE/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:91:9
    at /Users/idion/WorkSpace/codesquad/signup-1/FE/node_modules/graceful-fs/graceful-fs.js:115:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:61:3)
 @ multi ./src/main.js ./scss/main.scss main[1]
```

해결한 명령어 `npm install node-sass`

```
  "keywords": [],
  "dependencies": {
    "node-sass": "^4.13.1"
  }
```

**Comment by sungik-choi** [comment]
의존성 목록에서 삭제하고 풀리퀘스트 날리겠습니다.

**Comment by ksundong** [comment]
넵!

**Comment by sungik-choi** [comment]
최신화 하고 이슈 닫습니다.
